Cli
webion-hub/Webion.Templates pull request #2
Opened 2023-03-29 13:38 UTC by davidemesso

2023-03-30 08:05 UTC, cala-br requested changes

2023-03-30 08:05 UTC, cala-br commented on cli/Webion.Templates.Cli/Model/TemplateModel.cs
> +    public string Template { get; set; } = null!;
Mettili `required` con `{ get; init; }` se possibile

2023-03-30 08:05 UTC, cala-br commented on cli/Webion.Templates.Cli/Http/TemplatesClient.cs
> +
In `Program.cs` dentro `builder.ConfigureServices()` c'è `services.AddHttpClient<Interface, Impl>()` (`using Microsoft.Extensions.DependencyInjection`)

Rendilo iniettabile come `HttpClient`

Deve accettare l'HttpClient da costruttore ed averlo come campo `private readonly`, ed estendere l'interfaccia con i metodi del templates client

Dopo puoi iniettarlo usando l'interfaccia

2023-03-30 08:07 UTC, cala-br commented on cli/Webion.Templates.Cli/Commands/AddCommand.cs
> +}
Lo spinner può wrappare tante task, e con `ctx.Status()` puoi controllare il messaggio in base alla task

Mettilo anche per tutti gli altri handler che lo usano

2023-04-03 07:43 UTC, davidemesso commented on Webion.Templates.Api/Model/TemplateModel.cs
> +}
Serve c# 11 non so col fatto che gcp non supporta ancora le cose nuove, e comunque da errore

2023-04-04 08:00 UTC, cala-br requested changes

2023-04-04 08:00 UTC, cala-br commented on Webion.Templates.Api/Controllers/TemplateController.cs
> +    public async Task<IActionResult> ProcessTemplateAsync(
```suggestion
    public async Task<IActionResult> ProcessAsync(
```

2023-04-04 08:00 UTC, cala-br commented on cli/Webion.Templates.Cli/Http/TemplatesClient.cs
> +        var response = await _client.PostAsync($"/templates/", new StringContent(content, Encoding.UTF8, "application/json"), cancellationToken);
Esiste il metodo di estensione [PostAsJsonAsync](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.json.httpclientjsonextensions.postasjsonasync?view=net-8.0)

2023-04-04 08:00 UTC, cala-br commented on cli/Webion.Templates.Cli/Http/TemplatesClient.cs
> +        var templates = JsonConvert.DeserializeObject<List<string>>(json);
Ci sono i metodi di estensione `_client.GetFromJsonAsync<List<string>>()` e `response.Content.ReadFromJsonAsync<List<string>>()`

2023-04-04 08:00 UTC, cala-br commented on cli/Webion.Templates.Cli/Program.cs
> +                config.Url = "https://templates-api-p6erbd2ysa-nw.a.run.app";
Questo si può mettere come variabile d'ambiente?

2023-04-04 08:00 UTC, cala-br commented on cli/Webion.Templates.Cli/Commands/EditCommand.cs
> +                );
Esiste la possibilità di fare un Replace diretto su firebase? Perché se l'applicazione termina prima di CreateAsync rischi che sparisca il template

2023-04-05 14:48 UTC, cala-br requested changes

2023-04-05 14:48 UTC, cala-br commented on Webion.Firestore/Extensions/TypedDocumentSnapshot.cs
> +
Una cosa del genere non funziona?

```suggestion
    public async Task<bool> UpdateAsync<TProperty>(params (Expression<Func<TDoc, TProperty>> Field, TProperty Value) expressions)
    {
        var updateDict = new Dictionary<string, object?>();
        foreach (var e in expressions)
        {
           var name = GetPropertyName<TDoc, TProperty>(e.Field);
           updateDict.Add(name, e.Value);
        }

        var result = await _doc.Reference.UpdateAsync(updateDict);
        
        return result is not null;
    }

```

Usato come
```cs
await users.UpdateAsync(
    (u => u.Name, "Pippo"),
    (u => u.Surname, "Baudo")
);
```

2023-04-05 14:48 UTC, cala-br commented on Webion.Templates.Api/Controllers/TemplateController.cs
> +    public async Task<IActionResult> UpdateAsync([FromBody] string value, CancellationToken cancellationToken)
```suggestion
    public async Task<IActionResult> UpdateAsync([FromBody] string value)
```

2023-04-05 14:48 UTC, cala-br commented on cli/Webion.Templates.Cli/appsettings.json
Fai un `git rm --cached` di questo file e poi un commit

2023-04-13 08:13 UTC, cala-br requested changes

2023-04-13 08:13 UTC, cala-br commented on Webion.Templates.Http/Client/TemplatesClient.cs
> +        return (response.StatusCode != HttpStatusCode.NotFound);
E se è 500?

2023-09-19 17:51 UTC, cala-br commented
@davidemesso Ma questa pull request?

2023-09-19 17:52 UTC, cala-br approved these changes

2023-09-19 17:52 UTC, davidemesso commented
> @davidemesso Ma questa pull request?

È ancora usata sta roba?

2023-09-19 17:52 UTC, merged

2023-09-20 08:16 UTC, cala-br commented
> > @davidemesso Ma questa pull request?
> 
> È ancora usata sta roba?

Boh era mergiabile, ho mergiato